# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f889d8c8013e2b533c8487f97c39572d407feb26f7c04812a0571011d8aa5ce543c441a426081fc1ed150b28a17fe33533a795423da06dcea210fcc595bb4c61

test:
  secret_key_base: 6a7b24b482da7ce4a2f33eb606f4e468b641f42b28b97415f3d886f73873d64fcca9513f2866acb8432a67fc2112bd0578528b0620028f6a945ad5ce7cf4d86f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
